apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-exporter-ingress
  namespace: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: node-exporter.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-exporter-service
            port:
              number: 9100
