apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alert-manager-ingress
  namespace: grafana
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: alert-manager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alert-manager-service
            port:
              number: 9093
