apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: grafana
data:
  grafana_organization_name: 'MY_ORGANIZATION'
  grafana_organization_theme: 'dark'
  grafana_organization_weekstart: 'monday'
  grafana_organization_timezone: 'Europe/Warsaw'
  instance_name: 'Grafana Monitoring'
