---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo
  labels:
    client: "odoo-app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      # securityContext:
      #   runAsUser: 10000
      #   runAsNonRoot: true
      #   runAsGroup: 10001
      #   fsGroup: 10001 
      containers:
      - name: odoo
        image: docker.io/bitnami/odoo:16
        imagePullPolicy: Always
        ports:
        - containerPort: 8069
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: http
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /index.html
            port: http
          failureThreshold: 1
          periodSeconds: 10
        env:
        - name: ODOO_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: odoo-configmap
              key: DB_USER
        - name: ODOO_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: odoo-configmap
              key: DB_USER
        - name: ODOO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-secret
              key: DB_PASSWORD
        - name: ODOO_DATABASE_PORT_NUMBER
          valueFrom:
            configMapKeyRef:
              name: odoo-configmap
              key: DATABASE_PORT_NUMBER
        - name: ODOO_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: odoo-configmap
              key: DATABASE_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: odoo
spec:
  ports:
  - port: 80
    targetPort: 8069
  type: ClusterIP
  selector:
    app: odoo