kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: grafana
  name: deny-traffic-to-grafana-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          client: "grafana-app"